from __future__ import annotations

import json
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal, ROUND_HALF_UP
from time import perf_counter

from sqlalchemy import or_
from sqlalchemy.orm import Session, joinedload

from backend.crud.company import get_company_by_id
from backend.crud.shareholder import get_entity_by_company_id
from backend.models.company import Company
from backend.models.control_relationship import ControlRelationship
from backend.models.country_attribution import CountryAttribution
from backend.models.shareholder import ShareholderEntity, ShareholderStructure
from backend.shareholder_relations import build_equity_relationship_clause


AUTO_NOTE = "AUTO: generated by ownership penetration"
ZERO = Decimal("0")
HUNDRED = Decimal("100")
PCT_QUANT = Decimal("0.0001")


@dataclass(slots=True)
class OwnershipPath:
    entity_ids: list[int]
    entity_names: list[str]
    edge_ratios_pct: list[Decimal]
    path_ratio_pct: Decimal


@dataclass(slots=True)
class OwnershipAnalysisContext:
    as_of: date
    company_map: dict[int, Company]
    entity_map: dict[int, ShareholderEntity]
    entity_by_company_id: dict[int, ShareholderEntity]
    incoming_map: dict[int, list[ShareholderStructure]]


def _normalize_as_of(as_of: date | datetime | None) -> date:
    if as_of is None:
        return date.today()
    if isinstance(as_of, datetime):
        return as_of.date()
    return as_of


def _quantize_pct(value: Decimal) -> Decimal:
    return value.quantize(PCT_QUANT, rounding=ROUND_HALF_UP)


def _to_decimal(value: Decimal | None) -> Decimal:
    if value is None:
        return ZERO
    return Decimal(value)


def _serialize_decimal(value: Decimal) -> str:
    return format(_quantize_pct(value), "f")


def _serialize_ratio(value: Decimal | None) -> str | None:
    if value is None:
        return None
    return _serialize_decimal(_to_decimal(value))


def _deserialize_json(value: str | None):
    if value is None:
        return None
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


def _load_company_map(db: Session) -> dict[int, Company]:
    companies = db.query(Company).order_by(Company.id.asc()).all()
    return {company.id: company for company in companies}


def _load_entity_map(db: Session) -> dict[int, ShareholderEntity]:
    entities = (
        db.query(ShareholderEntity)
        .options(joinedload(ShareholderEntity.company))
        .order_by(ShareholderEntity.id.asc())
        .all()
    )
    return {entity.id: entity for entity in entities}


def _build_entity_by_company_id(
    entity_map: dict[int, ShareholderEntity],
) -> dict[int, ShareholderEntity]:
    entity_by_company_id: dict[int, ShareholderEntity] = {}
    for entity_id in sorted(entity_map):
        entity = entity_map[entity_id]
        if entity.company_id is None:
            continue
        entity_by_company_id.setdefault(entity.company_id, entity)
    return entity_by_company_id


def _load_eligible_edges(
    db: Session,
    as_of: date,
) -> dict[int, list[ShareholderStructure]]:
    edges = (
        db.query(ShareholderStructure)
        .filter(ShareholderStructure.is_current.is_(True))
        .filter(ShareholderStructure.is_direct.is_(True))
        .filter(build_equity_relationship_clause(ShareholderStructure))
        .filter(
            or_(
                ShareholderStructure.effective_date.is_(None),
                ShareholderStructure.effective_date <= as_of,
            )
        )
        .filter(
            or_(
                ShareholderStructure.expiry_date.is_(None),
                ShareholderStructure.expiry_date >= as_of,
            )
        )
        .order_by(ShareholderStructure.id.asc())
        .all()
    )

    incoming_map: dict[int, list[ShareholderStructure]] = defaultdict(list)
    for edge in edges:
        incoming_map[edge.to_entity_id].append(edge)

    for to_entity_id, incoming_edges in incoming_map.items():
        incoming_map[to_entity_id] = sorted(
            incoming_edges,
            key=lambda item: (-_to_decimal(item.holding_ratio), item.id),
        )

    return incoming_map


def build_ownership_analysis_context(
    db: Session,
    as_of: date | datetime | None = None,
) -> OwnershipAnalysisContext:
    as_of_date = _normalize_as_of(as_of)
    company_map = _load_company_map(db)
    entity_map = _load_entity_map(db)

    return OwnershipAnalysisContext(
        as_of=as_of_date,
        company_map=company_map,
        entity_map=entity_map,
        entity_by_company_id=_build_entity_by_company_id(entity_map),
        incoming_map=_load_eligible_edges(db, as_of_date),
    )


def _resolve_company_and_target_entity(
    db: Session,
    company_id: int,
    context: OwnershipAnalysisContext | None = None,
) -> tuple[Company, ShareholderEntity]:
    if context is None:
        company = get_company_by_id(db, company_id)
        target_entity = get_entity_by_company_id(db, company_id)
    else:
        company = context.company_map.get(company_id)
        target_entity = context.entity_by_company_id.get(company_id)

    if company is None:
        raise ValueError("Company not found.")
    if target_entity is None:
        raise ValueError("Mapped shareholder entity not found for company.")

    return company, target_entity


def _resolve_controller_country(
    controller_entity: ShareholderEntity | None,
) -> str | None:
    if controller_entity is None:
        return None
    if controller_entity.country:
        return controller_entity.country
    if controller_entity.company is not None:
        return controller_entity.company.incorporation_country
    return None


def _serialize_paths(paths: list[OwnershipPath]) -> str:
    payload = []
    ordered_paths = sorted(
        paths,
        key=lambda item: (-item.path_ratio_pct, item.entity_ids),
    )
    for path in ordered_paths:
        payload.append(
            {
                "path_entity_ids": path.entity_ids,
                "path_entity_names": path.entity_names,
                "edge_holding_ratio_pct": [
                    _serialize_decimal(value) for value in path.edge_ratios_pct
                ],
                "path_ratio_pct": _serialize_decimal(path.path_ratio_pct),
            }
        )
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _build_basis_payload(
    *,
    as_of: date,
    total_ratio_pct: Decimal,
    path_count: int,
    target_entity_id: int,
) -> str:
    payload = {
        "analysis": "ownership_penetration",
        "as_of": as_of.isoformat(),
        "path_count": path_count,
        "target_entity_id": target_entity_id,
        "total_ratio_pct": _serialize_decimal(total_ratio_pct),
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _build_country_basis_payload(
    *,
    as_of: date,
    attribution_type: str,
    actual_controller_entity_id: int | None,
    actual_control_country: str,
) -> str:
    payload = {
        "analysis": "ownership_penetration",
        "as_of": as_of.isoformat(),
        "attribution_type": attribution_type,
        "actual_control_country": actual_control_country,
        "actual_controller_entity_id": actual_controller_entity_id,
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _collect_candidate_paths(
    *,
    target_entity: ShareholderEntity,
    entity_map: dict[int, ShareholderEntity],
    incoming_map: dict[int, list[ShareholderStructure]],
    max_depth: int,
    min_path_ratio_pct: Decimal,
) -> tuple[dict[int, Decimal], dict[int, list[OwnershipPath]]]:
    totals_by_entity_id: dict[int, Decimal] = defaultdict(lambda: ZERO)
    paths_by_entity_id: dict[int, list[OwnershipPath]] = defaultdict(list)

    def dfs(
        current_entity_id: int,
        current_chain_ids: list[int],
        current_edge_ratios: list[Decimal],
        current_ratio_pct: Decimal,
        visited_entity_ids: set[int],
    ) -> None:
        next_depth = len(current_chain_ids)
        if next_depth > max_depth:
            return

        for edge in incoming_map.get(current_entity_id, []):
            upstream_entity_id = edge.from_entity_id
            if upstream_entity_id in visited_entity_ids:
                continue

            edge_ratio_pct = _to_decimal(edge.holding_ratio)
            if edge_ratio_pct <= ZERO:
                continue

            path_ratio_pct = current_ratio_pct * edge_ratio_pct / HUNDRED
            if path_ratio_pct < min_path_ratio_pct:
                continue

            upstream_entity = entity_map.get(upstream_entity_id)
            if upstream_entity is None:
                continue

            entity_ids = [upstream_entity_id, *current_chain_ids]
            entity_names = [
                entity_map[entity_id].entity_name for entity_id in entity_ids
            ]
            edge_ratios = [edge_ratio_pct, *current_edge_ratios]

            totals_by_entity_id[upstream_entity_id] += path_ratio_pct
            paths_by_entity_id[upstream_entity_id].append(
                OwnershipPath(
                    entity_ids=entity_ids,
                    entity_names=entity_names,
                    edge_ratios_pct=edge_ratios,
                    path_ratio_pct=path_ratio_pct,
                )
            )

            dfs(
                upstream_entity_id,
                entity_ids,
                edge_ratios,
                path_ratio_pct,
                {upstream_entity_id, *visited_entity_ids},
            )

    dfs(target_entity.id, [target_entity.id], [], HUNDRED, {target_entity.id})

    capped_totals = {
        entity_id: min(total_ratio_pct, HUNDRED)
        for entity_id, total_ratio_pct in totals_by_entity_id.items()
    }
    return capped_totals, paths_by_entity_id


def _prepare_candidate_results(
    *,
    company: Company,
    target_entity: ShareholderEntity,
    context: OwnershipAnalysisContext,
    max_depth: int,
    min_path_ratio_pct: Decimal,
    majority_threshold_pct: Decimal,
    disclosure_threshold_pct: Decimal,
) -> dict:
    totals_by_entity_id, paths_by_entity_id = _collect_candidate_paths(
        target_entity=target_entity,
        entity_map=context.entity_map,
        incoming_map=context.incoming_map,
        max_depth=max_depth,
        min_path_ratio_pct=min_path_ratio_pct,
    )

    candidate_results = []
    for entity_id, total_ratio_pct in totals_by_entity_id.items():
        if total_ratio_pct < disclosure_threshold_pct:
            continue

        controller_entity = context.entity_map[entity_id]
        candidate_results.append(
            {
                "entity": controller_entity,
                "entity_id": controller_entity.id,
                "total_ratio_pct": total_ratio_pct,
                "paths": paths_by_entity_id[entity_id],
            }
        )

    candidate_results.sort(
        key=lambda item: (-item["total_ratio_pct"], item["entity_id"]),
    )

    actual_controller = next(
        (
            item
            for item in candidate_results
            if item["total_ratio_pct"] >= majority_threshold_pct
        ),
        None,
    )

    actual_control_country = company.incorporation_country
    attribution_type = "fallback_incorporation"
    actual_controller_entity_id: int | None = None
    if actual_controller is not None:
        actual_controller_entity_id = actual_controller["entity_id"]
        actual_control_country = (
            _resolve_controller_country(actual_controller["entity"])
            or company.incorporation_country
        )
        attribution_type = "direct_equity_control"

    return {
        "company": company,
        "target_entity": target_entity,
        "candidate_results": candidate_results,
        "actual_controller": actual_controller,
        "actual_controller_entity_id": actual_controller_entity_id,
        "actual_control_country": actual_control_country,
        "attribution_type": attribution_type,
    }


def _apply_company_analysis_records(
    db: Session,
    prepared_result: dict,
    *,
    as_of: date,
) -> dict:
    company: Company = prepared_result["company"]
    target_entity: ShareholderEntity = prepared_result["target_entity"]
    candidate_results: list[dict] = prepared_result["candidate_results"]
    actual_controller = prepared_result["actual_controller"]
    actual_controller_entity_id: int | None = prepared_result[
        "actual_controller_entity_id"
    ]
    actual_control_country: str = prepared_result["actual_control_country"]
    attribution_type: str = prepared_result["attribution_type"]

    (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company.id)
        .filter(ControlRelationship.notes.like("AUTO:%"))
        .delete(synchronize_session=False)
    )
    (
        db.query(CountryAttribution)
        .filter(CountryAttribution.company_id == company.id)
        .filter(CountryAttribution.notes.like("AUTO:%"))
        .delete(synchronize_session=False)
    )

    for item in candidate_results:
        controller_entity = item["entity"]
        total_ratio_pct = min(item["total_ratio_pct"], HUNDRED)
        is_actual_controller = (
            actual_controller is not None
            and controller_entity.id == actual_controller["entity_id"]
        )
        control_type = (
            "direct_equity_control"
            if is_actual_controller
            else "significant_equity"
        )

        db.add(
            ControlRelationship(
                company_id=company.id,
                controller_entity_id=controller_entity.id,
                controller_name=controller_entity.entity_name,
                controller_type=controller_entity.entity_type,
                control_type=control_type,
                control_ratio=_quantize_pct(total_ratio_pct),
                control_path=_serialize_paths(item["paths"]),
                is_actual_controller=is_actual_controller,
                basis=_build_basis_payload(
                    as_of=as_of,
                    total_ratio_pct=total_ratio_pct,
                    path_count=len(item["paths"]),
                    target_entity_id=target_entity.id,
                ),
                notes=AUTO_NOTE,
                control_mode="numeric",
                semantic_flags=None,
                review_status="auto",
            )
        )

    db.add(
        CountryAttribution(
            company_id=company.id,
            incorporation_country=company.incorporation_country,
            listing_country=company.listing_country,
            actual_control_country=actual_control_country,
            attribution_type=attribution_type,
            basis=_build_country_basis_payload(
                as_of=as_of,
                attribution_type=attribution_type,
                actual_controller_entity_id=actual_controller_entity_id,
                actual_control_country=actual_control_country,
            ),
            is_manual=False,
            notes=AUTO_NOTE,
            source_mode=(
                "fallback_rule"
                if attribution_type.startswith("fallback_")
                else "control_chain_analysis"
            ),
        )
    )

    db.flush()

    return {
        "company_id": company.id,
        "target_entity_id": target_entity.id,
        "as_of": as_of.isoformat(),
        "actual_controller_entity_id": actual_controller_entity_id,
        "control_relationship_count": len(candidate_results),
        "country_attribution_type": attribution_type,
        "controller_candidates": [
            {
                "entity_id": item["entity_id"],
                "entity_name": item["entity"].entity_name,
                "total_ratio_pct": _serialize_decimal(item["total_ratio_pct"]),
                "path_count": len(item["paths"]),
                "is_actual_controller": (
                    actual_controller is not None
                    and item["entity_id"] == actual_controller["entity_id"]
                ),
            }
            for item in candidate_results
        ],
    }


def _refresh_company_control_analysis_with_context(
    db: Session,
    company_id: int,
    *,
    context: OwnershipAnalysisContext,
    max_depth: int,
    min_path_ratio_pct: Decimal,
    majority_threshold_pct: Decimal,
    disclosure_threshold_pct: Decimal,
) -> dict:
    company, target_entity = _resolve_company_and_target_entity(
        db,
        company_id,
        context,
    )
    prepared_result = _prepare_candidate_results(
        company=company,
        target_entity=target_entity,
        context=context,
        max_depth=max_depth,
        min_path_ratio_pct=min_path_ratio_pct,
        majority_threshold_pct=majority_threshold_pct,
        disclosure_threshold_pct=disclosure_threshold_pct,
    )
    return _apply_company_analysis_records(
        db,
        prepared_result,
        as_of=context.as_of,
    )


def refresh_company_control_analysis(
    db: Session,
    company_id: int,
    as_of: date | datetime | None = None,
    max_depth: int = 10,
    min_path_ratio_pct: Decimal = Decimal("0.01"),
    majority_threshold_pct: Decimal = Decimal("50.0"),
    disclosure_threshold_pct: Decimal = Decimal("25.0"),
) -> dict:
    if max_depth < 1:
        raise ValueError("max_depth must be at least 1.")
    if min_path_ratio_pct < ZERO:
        raise ValueError("min_path_ratio_pct must be non-negative.")

    context = build_ownership_analysis_context(db, as_of)

    try:
        result = _refresh_company_control_analysis_with_context(
            db,
            company_id,
            context=context,
            max_depth=max_depth,
            min_path_ratio_pct=min_path_ratio_pct,
            majority_threshold_pct=majority_threshold_pct,
            disclosure_threshold_pct=disclosure_threshold_pct,
        )
        db.commit()
        return result
    except Exception:
        db.rollback()
        raise


def refresh_all_companies_control_analysis(
    db: Session,
    batch_size: int = 100,
) -> dict:
    if batch_size < 1:
        raise ValueError("batch_size must be at least 1.")

    started_at = perf_counter()
    context = build_ownership_analysis_context(db)
    company_ids = sorted(context.company_map)
    total = len(company_ids)
    success_count = 0
    failed_count = 0
    per_company_durations: list[float] = []

    print("[START] control analysis")

    for batch_start in range(0, total, batch_size):
        batch_end = min(batch_start + batch_size, total)
        batch_company_ids = company_ids[batch_start:batch_end]
        batch_success_count = 0

        print(f"[BATCH] processing {batch_start + 1}-{batch_end} / {total}")

        for company_id in batch_company_ids:
            company_started_at = perf_counter()
            try:
                with db.begin_nested():
                    result = _refresh_company_control_analysis_with_context(
                        db,
                        company_id,
                        context=context,
                        max_depth=10,
                        min_path_ratio_pct=Decimal("0.01"),
                        majority_threshold_pct=Decimal("50.0"),
                        disclosure_threshold_pct=Decimal("25.0"),
                    )
                success_count += 1
                batch_success_count += 1
                print(
                    f"[COMPANY] {company_id} done, "
                    f"controllers={result['control_relationship_count']}"
                )
            except Exception as exc:
                failed_count += 1
                db.expire_all()
                print(f"[COMPANY] {company_id} failed: {exc}")
            finally:
                per_company_durations.append(perf_counter() - company_started_at)

        try:
            db.commit()
            print(f"[BATCH] committed {len(batch_company_ids)}")
        except Exception as exc:
            db.rollback()
            success_count -= batch_success_count
            failed_count += batch_success_count
            print(
                f"[BATCH] commit failed {batch_start + 1}-{batch_end} / {total}: {exc}"
            )

    total_duration_seconds = perf_counter() - started_at
    average_duration_seconds = (
        sum(per_company_durations) / len(per_company_durations)
        if per_company_durations
        else 0.0
    )

    print(f"[END] total processed = {total}")

    return {
        "total_processed": total,
        "success_count": success_count,
        "failed_count": failed_count,
        "average_duration_seconds": average_duration_seconds,
        "total_duration_seconds": total_duration_seconds,
    }


def _serialize_control_relationship_response(
    relationship: ControlRelationship,
) -> dict:
    return {
        "id": relationship.id,
        "company_id": relationship.company_id,
        "controller_entity_id": relationship.controller_entity_id,
        "controller_name": relationship.controller_name,
        "controller_type": relationship.controller_type,
        "control_type": relationship.control_type,
        "control_ratio": _serialize_ratio(relationship.control_ratio),
        "control_path": _deserialize_json(relationship.control_path),
        "is_actual_controller": relationship.is_actual_controller,
        "basis": relationship.basis,
        "notes": relationship.notes,
        "control_mode": relationship.control_mode,
        "semantic_flags": _deserialize_json(relationship.semantic_flags),
        "review_status": relationship.review_status,
        "created_at": relationship.created_at.isoformat(),
        "updated_at": relationship.updated_at.isoformat(),
    }


def get_company_control_chain_data(db: Session, company_id: int) -> dict:
    relationships = (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company_id)
        .order_by(
            ControlRelationship.control_ratio.is_(None),
            ControlRelationship.control_ratio.desc(),
            ControlRelationship.id.asc(),
        )
        .all()
    )

    return {
        "company_id": company_id,
        "controller_count": len(relationships),
        "control_relationships": [
            _serialize_control_relationship_response(relationship)
            for relationship in relationships
        ],
    }


def get_company_actual_controller_data(db: Session, company_id: int) -> dict:
    relationships = (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company_id)
        .filter(ControlRelationship.is_actual_controller.is_(True))
        .order_by(
            ControlRelationship.control_ratio.is_(None),
            ControlRelationship.control_ratio.desc(),
            ControlRelationship.id.asc(),
        )
        .all()
    )

    return {
        "company_id": company_id,
        "controller_count": len(relationships),
        "actual_controllers": [
            _serialize_control_relationship_response(relationship)
            for relationship in relationships
        ],
    }


def get_company_country_attribution_data(db: Session, company_id: int) -> dict:
    country_attribution = (
        db.query(CountryAttribution)
        .filter(CountryAttribution.company_id == company_id)
        .order_by(CountryAttribution.id.desc())
        .first()
    )

    if country_attribution is None:
        return {
            "company_id": company_id,
            "message": "No country attribution data found for this company.",
            "actual_control_country": None,
            "attribution_type": None,
            "basis": None,
            "source_mode": None,
        }

    return {
        "company_id": company_id,
        "actual_control_country": country_attribution.actual_control_country,
        "attribution_type": country_attribution.attribution_type,
        "basis": country_attribution.basis,
        "source_mode": country_attribution.source_mode,
    }
