from __future__ import annotations

import json
import os
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal, ROUND_HALF_UP
from time import perf_counter

from sqlalchemy import or_
from sqlalchemy.orm import Session, joinedload

from backend.analysis.control_inference import (
    ControllerCandidate,
    ControlInferenceContext,
    ControlInferenceResult,
    PathState,
    build_control_context,
    infer_controllers,
    serialize_pct_score,
    serialize_unit_score,
    unit_to_pct,
)
from backend.crud.company import get_company_by_id
from backend.crud.shareholder import get_entity_by_company_id
from backend.models.company import Company
from backend.models.control_relationship import ControlRelationship
from backend.models.country_attribution import CountryAttribution
from backend.models.shareholder import ShareholderEntity, ShareholderStructure
from backend.shareholder_relations import (
    build_equity_relationship_clause,
    canonicalize_attribution_type,
    canonicalize_control_type,
)


AUTO_NOTE = "AUTO: generated by ownership penetration"
ZERO = Decimal("0")
ONE = Decimal("1")
HUNDRED = Decimal("100")
PCT_QUANT = Decimal("0.0001")
UNIFIED_ENGINE_ENV = "CONTROL_INFERENCE_ENGINE"
DISABLE_LEGACY_FALLBACK_ENV = "CONTROL_INFERENCE_DISABLE_LEGACY_FALLBACK"


@dataclass(slots=True)
class OwnershipPath:
    entity_ids: list[int]
    entity_names: list[str]
    edge_ids: list[int]
    edge_ratios_pct: list[Decimal]
    path_ratio_pct: Decimal


@dataclass(slots=True)
class OwnershipAnalysisContext:
    as_of: date
    company_map: dict[int, Company]
    entity_map: dict[int, ShareholderEntity]
    entity_by_company_id: dict[int, ShareholderEntity]
    incoming_map: dict[int, list[ShareholderStructure]]


def _normalize_as_of(as_of: date | datetime | None) -> date:
    if as_of is None:
        return date.today()
    if isinstance(as_of, datetime):
        return as_of.date()
    return as_of


def _quantize_pct(value: Decimal) -> Decimal:
    return value.quantize(PCT_QUANT, rounding=ROUND_HALF_UP)


def _to_decimal(value: Decimal | None) -> Decimal:
    if value is None:
        return ZERO
    return Decimal(value)


def _serialize_decimal(value: Decimal) -> str:
    return format(_quantize_pct(value), "f")


def _serialize_ratio(value: Decimal | None) -> str | None:
    if value is None:
        return None
    return _serialize_decimal(_to_decimal(value))


def _serialize_probability(value: Decimal | str | None) -> str | None:
    if value is None:
        return None
    normalized = Decimal(str(value))
    if normalized > ONE:
        normalized /= HUNDRED
    normalized = min(ONE, max(ZERO, normalized))
    return _serialize_decimal(normalized)


def _serialize_pct_from_any(value: Decimal | str | None) -> str | None:
    if value is None:
        return None
    normalized = Decimal(str(value))
    if normalized <= ONE:
        normalized *= HUNDRED
    return _serialize_decimal(normalized)


def _parse_json_list(value: str | list | tuple | set | None) -> list[str] | None:
    if value is None:
        return None
    payload = value
    if isinstance(value, str):
        parsed = _deserialize_json(value)
        payload = parsed if parsed is not None else value
    if isinstance(payload, (list, tuple, set)):
        items = [
            str(item).strip()
            for item in payload
            if str(item).strip()
        ]
        return sorted(dict.fromkeys(items)) or None
    if isinstance(payload, str) and payload.strip():
        return [payload.strip()]
    return None


def _deserialize_json(value: str | None):
    if value is None:
        return None
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


def _canonical_control_type(value: str | None) -> str | None:
    return canonicalize_control_type(value)


def _canonical_attribution_type(value: str | None) -> str | None:
    return canonicalize_attribution_type(value)


def _load_company_map(db: Session) -> dict[int, Company]:
    companies = db.query(Company).order_by(Company.id.asc()).all()
    return {company.id: company for company in companies}


def _load_entity_map(db: Session) -> dict[int, ShareholderEntity]:
    entities = (
        db.query(ShareholderEntity)
        .options(joinedload(ShareholderEntity.company))
        .order_by(ShareholderEntity.id.asc())
        .all()
    )
    return {entity.id: entity for entity in entities}


def _build_entity_by_company_id(
    entity_map: dict[int, ShareholderEntity],
) -> dict[int, ShareholderEntity]:
    entity_by_company_id: dict[int, ShareholderEntity] = {}
    for entity_id in sorted(entity_map):
        entity = entity_map[entity_id]
        if entity.company_id is None:
            continue
        entity_by_company_id.setdefault(entity.company_id, entity)
    return entity_by_company_id


def _load_eligible_edges(
    db: Session,
    as_of: date,
) -> dict[int, list[ShareholderStructure]]:
    edges = (
        db.query(ShareholderStructure)
        .filter(ShareholderStructure.is_current.is_(True))
        .filter(ShareholderStructure.is_direct.is_(True))
        .filter(build_equity_relationship_clause(ShareholderStructure))
        .filter(
            or_(
                ShareholderStructure.effective_date.is_(None),
                ShareholderStructure.effective_date <= as_of,
            )
        )
        .filter(
            or_(
                ShareholderStructure.expiry_date.is_(None),
                ShareholderStructure.expiry_date >= as_of,
            )
        )
        .order_by(ShareholderStructure.id.asc())
        .all()
    )

    incoming_map: dict[int, list[ShareholderStructure]] = defaultdict(list)
    for edge in edges:
        incoming_map[edge.to_entity_id].append(edge)

    for to_entity_id, incoming_edges in incoming_map.items():
        incoming_map[to_entity_id] = sorted(
            incoming_edges,
            key=lambda item: (-_to_decimal(item.holding_ratio), item.id),
        )

    return incoming_map


def build_ownership_analysis_context(
    db: Session,
    as_of: date | datetime | None = None,
) -> OwnershipAnalysisContext:
    as_of_date = _normalize_as_of(as_of)
    company_map = _load_company_map(db)
    entity_map = _load_entity_map(db)

    return OwnershipAnalysisContext(
        as_of=as_of_date,
        company_map=company_map,
        entity_map=entity_map,
        entity_by_company_id=_build_entity_by_company_id(entity_map),
        incoming_map=_load_eligible_edges(db, as_of_date),
    )


def _resolve_company_and_target_entity(
    db: Session,
    company_id: int,
    context: OwnershipAnalysisContext | None = None,
) -> tuple[Company, ShareholderEntity]:
    if context is None:
        company = get_company_by_id(db, company_id)
        target_entity = get_entity_by_company_id(db, company_id)
    else:
        company = context.company_map.get(company_id)
        target_entity = context.entity_by_company_id.get(company_id)

    if company is None:
        raise ValueError("Company not found.")
    if target_entity is None:
        raise ValueError("Mapped shareholder entity not found for company.")

    return company, target_entity


def _resolve_controller_country(
    controller_entity: ShareholderEntity | None,
) -> str | None:
    if controller_entity is None:
        return None
    if controller_entity.country:
        return controller_entity.country
    if controller_entity.company is not None:
        return controller_entity.company.incorporation_country
    return None


def _serialize_paths(paths: list[OwnershipPath]) -> str:
    payload = []
    ordered_paths = sorted(
        paths,
        key=lambda item: (-item.path_ratio_pct, item.entity_ids),
    )
    for path in ordered_paths:
        path_score = path.path_ratio_pct / HUNDRED
        payload.append(
            {
                "path_entity_ids": path.entity_ids,
                "path_entity_names": path.entity_names,
                "edge_ids": path.edge_ids,
                "edges": [
                    {
                        "structure_id": (
                            path.edge_ids[index]
                            if index < len(path.edge_ids)
                            else None
                        ),
                        "from_entity_id": path.entity_ids[index],
                        "to_entity_id": path.entity_ids[index + 1],
                        "relation_type": "equity",
                        "relation_role": "ownership",
                        "numeric_factor": _serialize_probability(value / HUNDRED),
                        "semantic_factor": "1.0000",
                        "confidence_weight": "1.0000",
                        "flags": ["equity"],
                        "evidence_summary": None,
                    }
                    for index, value in enumerate(path.edge_ratios_pct)
                ],
                "numeric_prod": _serialize_probability(path_score),
                "semantic_prod": "1.0000",
                "confidence_prod": "1.0000",
                "path_score": _serialize_probability(path_score),
                "path_score_pct": _serialize_decimal(path.path_ratio_pct),
                "semantic_flags": None,
            }
        )
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _build_basis_payload(
    *,
    as_of: date,
    classification: str,
    total_ratio_pct: Decimal,
    path_count: int,
    top_paths: list[OwnershipPath],
    target_entity_id: int,
) -> str:
    payload = {
        "analysis": "ownership_penetration",
        "aggregator": "sum_cap",
        "as_of": as_of.isoformat(),
        "classification": classification,
        "control_mode": "numeric",
        "evidence_summary": [],
        "path_count": path_count,
        "semantic_flags": None,
        "target_entity_id": target_entity_id,
        "top_paths": json.loads(_serialize_paths(top_paths[:3])),
        "total_confidence": "1.0000",
        "total_score": _serialize_probability(total_ratio_pct / HUNDRED),
        "total_ratio_pct": _serialize_decimal(total_ratio_pct),
        "total_score_pct": _serialize_decimal(total_ratio_pct),
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _build_country_basis_payload(
    *,
    as_of: date,
    attribution_type: str,
    actual_controller_entity_id: int | None,
    actual_control_country: str,
    total_ratio_pct: Decimal | None,
    top_paths: list[OwnershipPath] | None,
) -> str:
    if attribution_type == "fallback_incorporation":
        evidence_summary = [
            "fallback to incorporation country because no controlling candidate met threshold"
        ]
        top_paths_payload = []
        total_score = "0.0000"
        total_confidence = "0.0000"
        semantic_flags = None
    else:
        evidence_summary = []
        top_paths_payload = json.loads(_serialize_paths((top_paths or [])[:3]))
        total_score = _serialize_probability((total_ratio_pct or ZERO) / HUNDRED)
        total_confidence = "1.0000"
        semantic_flags = None
    payload = {
        "analysis": "ownership_penetration",
        "aggregator": "sum_cap",
        "as_of": as_of.isoformat(),
        "classification": attribution_type,
        "attribution_type": attribution_type,
        "actual_control_country": actual_control_country,
        "actual_controller_entity_id": actual_controller_entity_id,
        "evidence_summary": evidence_summary,
        "semantic_flags": semantic_flags,
        "top_paths": top_paths_payload,
        "total_confidence": total_confidence,
        "total_score": total_score,
        "total_score_pct": _serialize_pct_from_any(total_score),
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _collect_candidate_paths(
    *,
    target_entity: ShareholderEntity,
    entity_map: dict[int, ShareholderEntity],
    incoming_map: dict[int, list[ShareholderStructure]],
    max_depth: int,
    min_path_ratio_pct: Decimal,
) -> tuple[dict[int, Decimal], dict[int, list[OwnershipPath]]]:
    totals_by_entity_id: dict[int, Decimal] = defaultdict(lambda: ZERO)
    paths_by_entity_id: dict[int, list[OwnershipPath]] = defaultdict(list)

    def dfs(
        current_entity_id: int,
        current_chain_ids: list[int],
        current_edge_ids: list[int],
        current_edge_ratios: list[Decimal],
        current_ratio_pct: Decimal,
        visited_entity_ids: set[int],
    ) -> None:
        next_depth = len(current_chain_ids)
        if next_depth > max_depth:
            return

        for edge in incoming_map.get(current_entity_id, []):
            upstream_entity_id = edge.from_entity_id
            if upstream_entity_id in visited_entity_ids:
                continue

            edge_ratio_pct = _to_decimal(edge.holding_ratio)
            if edge_ratio_pct <= ZERO:
                continue

            path_ratio_pct = current_ratio_pct * edge_ratio_pct / HUNDRED
            if path_ratio_pct < min_path_ratio_pct:
                continue

            upstream_entity = entity_map.get(upstream_entity_id)
            if upstream_entity is None:
                continue

            entity_ids = [upstream_entity_id, *current_chain_ids]
            entity_names = [
                entity_map[entity_id].entity_name for entity_id in entity_ids
            ]
            edge_ids = [edge.id, *current_edge_ids]
            edge_ratios = [edge_ratio_pct, *current_edge_ratios]

            totals_by_entity_id[upstream_entity_id] += path_ratio_pct
            paths_by_entity_id[upstream_entity_id].append(
                OwnershipPath(
                    entity_ids=entity_ids,
                    entity_names=entity_names,
                    edge_ids=edge_ids,
                    edge_ratios_pct=edge_ratios,
                    path_ratio_pct=path_ratio_pct,
                )
            )

            dfs(
                upstream_entity_id,
                entity_ids,
                edge_ids,
                edge_ratios,
                path_ratio_pct,
                {upstream_entity_id, *visited_entity_ids},
            )

    dfs(target_entity.id, [target_entity.id], [], [], HUNDRED, {target_entity.id})

    capped_totals = {
        entity_id: min(total_ratio_pct, HUNDRED)
        for entity_id, total_ratio_pct in totals_by_entity_id.items()
    }
    return capped_totals, paths_by_entity_id


def _prepare_candidate_results(
    *,
    company: Company,
    target_entity: ShareholderEntity,
    context: OwnershipAnalysisContext,
    max_depth: int,
    min_path_ratio_pct: Decimal,
    majority_threshold_pct: Decimal,
    disclosure_threshold_pct: Decimal,
) -> dict:
    totals_by_entity_id, paths_by_entity_id = _collect_candidate_paths(
        target_entity=target_entity,
        entity_map=context.entity_map,
        incoming_map=context.incoming_map,
        max_depth=max_depth,
        min_path_ratio_pct=min_path_ratio_pct,
    )

    candidate_results = []
    for entity_id, total_ratio_pct in totals_by_entity_id.items():
        if total_ratio_pct < disclosure_threshold_pct:
            continue

        controller_entity = context.entity_map[entity_id]
        candidate_results.append(
            {
                "entity": controller_entity,
                "entity_id": controller_entity.id,
                "total_ratio_pct": total_ratio_pct,
                "paths": paths_by_entity_id[entity_id],
            }
        )

    candidate_results.sort(
        key=lambda item: (-item["total_ratio_pct"], item["entity_id"]),
    )

    actual_controller = next(
        (
            item
            for item in candidate_results
            if item["total_ratio_pct"] >= majority_threshold_pct
        ),
        None,
    )

    actual_control_country = company.incorporation_country
    attribution_type = "fallback_incorporation"
    actual_controller_entity_id: int | None = None
    if actual_controller is not None:
        actual_controller_entity_id = actual_controller["entity_id"]
        actual_control_country = (
            _resolve_controller_country(actual_controller["entity"])
            or company.incorporation_country
        )
        attribution_type = "equity_control"

    return {
        "company": company,
        "target_entity": target_entity,
        "candidate_results": candidate_results,
        "actual_controller": actual_controller,
        "actual_controller_entity_id": actual_controller_entity_id,
        "actual_control_country": actual_control_country,
        "attribution_type": attribution_type,
    }


def _apply_company_analysis_records(
    db: Session,
    prepared_result: dict,
    *,
    as_of: date,
) -> dict:
    company: Company = prepared_result["company"]
    target_entity: ShareholderEntity = prepared_result["target_entity"]
    candidate_results: list[dict] = prepared_result["candidate_results"]
    actual_controller = prepared_result["actual_controller"]
    actual_controller_entity_id: int | None = prepared_result[
        "actual_controller_entity_id"
    ]
    actual_control_country: str = prepared_result["actual_control_country"]
    attribution_type: str = prepared_result["attribution_type"]

    (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company.id)
        .filter(ControlRelationship.notes.like("AUTO:%"))
        .delete(synchronize_session=False)
    )
    (
        db.query(CountryAttribution)
        .filter(CountryAttribution.company_id == company.id)
        .filter(CountryAttribution.notes.like("AUTO:%"))
        .delete(synchronize_session=False)
    )

    for item in candidate_results:
        controller_entity = item["entity"]
        total_ratio_pct = min(item["total_ratio_pct"], HUNDRED)
        is_actual_controller = (
            actual_controller is not None
            and controller_entity.id == actual_controller["entity_id"]
        )
        control_type = (
            "equity_control"
            if is_actual_controller
            else "significant_influence"
        )

        db.add(
            ControlRelationship(
                company_id=company.id,
                controller_entity_id=controller_entity.id,
                controller_name=controller_entity.entity_name,
                controller_type=controller_entity.entity_type,
                control_type=control_type,
                control_ratio=_quantize_pct(total_ratio_pct),
                control_path=_serialize_paths(item["paths"]),
                is_actual_controller=is_actual_controller,
                basis=_build_basis_payload(
                    as_of=as_of,
                    classification=control_type,
                    total_ratio_pct=total_ratio_pct,
                    path_count=len(item["paths"]),
                    top_paths=item["paths"],
                    target_entity_id=target_entity.id,
                ),
                notes=AUTO_NOTE,
                control_mode="numeric",
                semantic_flags=None,
                review_status="auto",
            )
        )

    db.add(
        CountryAttribution(
            company_id=company.id,
            incorporation_country=company.incorporation_country,
            listing_country=company.listing_country,
            actual_control_country=actual_control_country,
            attribution_type=attribution_type,
            basis=_build_country_basis_payload(
                as_of=as_of,
                attribution_type=attribution_type,
                actual_controller_entity_id=actual_controller_entity_id,
                actual_control_country=actual_control_country,
                total_ratio_pct=(
                    actual_controller["total_ratio_pct"]
                    if actual_controller is not None
                    else None
                ),
                top_paths=(
                    actual_controller["paths"]
                    if actual_controller is not None
                    else None
                ),
            ),
            is_manual=False,
            notes=AUTO_NOTE,
            source_mode=(
                "fallback_rule"
                if attribution_type.startswith("fallback_")
                else "control_chain_analysis"
            ),
        )
    )

    db.flush()

    return {
        "company_id": company.id,
        "target_entity_id": target_entity.id,
        "as_of": as_of.isoformat(),
        "actual_controller_entity_id": actual_controller_entity_id,
        "control_relationship_count": len(candidate_results),
        "country_attribution_type": attribution_type,
        "controller_candidates": [
            {
                "entity_id": item["entity_id"],
                "entity_name": item["entity"].entity_name,
                "total_ratio_pct": _serialize_decimal(item["total_ratio_pct"]),
                "path_count": len(item["paths"]),
                "is_actual_controller": (
                    actual_controller is not None
                    and item["entity_id"] == actual_controller["entity_id"]
                ),
            }
            for item in candidate_results
        ],
    }


def _refresh_company_control_analysis_with_context(
    db: Session,
    company_id: int,
    *,
    context: OwnershipAnalysisContext,
    max_depth: int,
    min_path_ratio_pct: Decimal,
    majority_threshold_pct: Decimal,
    disclosure_threshold_pct: Decimal,
) -> dict:
    company, target_entity = _resolve_company_and_target_entity(
        db,
        company_id,
        context,
    )
    prepared_result = _prepare_candidate_results(
        company=company,
        target_entity=target_entity,
        context=context,
        max_depth=max_depth,
        min_path_ratio_pct=min_path_ratio_pct,
        majority_threshold_pct=majority_threshold_pct,
        disclosure_threshold_pct=disclosure_threshold_pct,
    )
    return _apply_company_analysis_records(
        db,
        prepared_result,
        as_of=context.as_of,
    )


def _use_unified_control_engine() -> bool:
    return os.getenv(UNIFIED_ENGINE_ENV, "unified").strip().lower() != "legacy"


def _allow_legacy_fallback() -> bool:
    return os.getenv(DISABLE_LEGACY_FALLBACK_ENV, "").strip().lower() not in {
        "1",
        "true",
        "yes",
    }


def _pct_threshold_to_unit(value: Decimal) -> Decimal:
    return Decimal(value) / HUNDRED


def _semantic_flags_for_storage(flags: tuple[str, ...]) -> list[str] | None:
    semantic_flags = [flag for flag in flags if flag != "equity"]
    return semantic_flags or None


def _control_type_from_candidate(candidate: ControllerCandidate) -> str:
    flags = set(candidate.semantic_flags)
    if candidate.is_joint_control:
        return "joint_control"
    if candidate.control_level != "control":
        return "significant_influence"
    if candidate.control_mode == "numeric":
        return "equity_control"
    if candidate.control_mode == "mixed":
        return "mixed_control"
    if "board_control" in flags:
        return "board_control"
    return "agreement_control"


def _build_canonical_path_edges_from_factors(
    path_state: PathState,
) -> list[dict]:
    return [
        {
            "structure_id": factor.structure_id,
            "from_entity_id": factor.from_entity_id,
            "to_entity_id": factor.to_entity_id,
            "relation_type": factor.relation_type,
            "relation_role": factor.relation_role,
            "numeric_factor": serialize_unit_score(factor.numeric_factor),
            "semantic_factor": serialize_unit_score(factor.semantic_factor),
            "confidence_weight": serialize_unit_score(factor.confidence_weight),
            "flags": list(factor.flags),
            "evidence_summary": factor.evidence.get("evidence_summary"),
        }
        for factor in path_state.edge_factors
    ]


def _serialize_unified_path(
    path_state: PathState,
    *,
    context: ControlInferenceContext,
) -> dict:
    path_score = path_state.numeric_prod * path_state.semantic_prod
    return {
        "path_entity_ids": path_state.entity_ids,
        "path_entity_names": [
            context.entity_map[entity_id].entity_name
            for entity_id in path_state.entity_ids
            if entity_id in context.entity_map
        ],
        "edge_ids": path_state.edge_ids,
        "edges": _build_canonical_path_edges_from_factors(path_state),
        "numeric_prod": serialize_unit_score(path_state.numeric_prod),
        "semantic_prod": serialize_unit_score(path_state.semantic_prod),
        "confidence_prod": serialize_unit_score(path_state.conf_prod),
        "path_score": serialize_unit_score(path_score),
        "path_score_pct": serialize_pct_score(path_score),
        "semantic_flags": _semantic_flags_for_storage(path_state.flags),
    }


def _serialize_unified_paths(
    path_states: tuple[PathState, ...],
    *,
    context: ControlInferenceContext,
) -> str:
    payload = [
        _serialize_unified_path(path_state, context=context)
        for path_state in path_states
    ]
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _build_unified_basis_payload(
    *,
    result: ControlInferenceResult,
    candidate: ControllerCandidate,
    context: ControlInferenceContext,
) -> str:
    classification = _control_type_from_candidate(candidate)
    payload = {
        "analysis": "unified_control_inference_v1",
        "aggregator": result.aggregator,
        "as_of": context.as_of.isoformat(),
        "classification": classification,
        "control_mode": candidate.control_mode,
        "entity_id": candidate.controller_entity_id,
        "evidence_summary": list(candidate.evidence_summary),
        "path_count": len(candidate.path_states),
        "semantic_flags": _semantic_flags_for_storage(candidate.semantic_flags),
        "target_entity_id": result.target_entity.id,
        "top_paths": [
            _serialize_unified_path(path_state, context=context)
            for path_state in candidate.top_paths
        ],
        "total_confidence": serialize_unit_score(candidate.total_confidence),
        "total_score": serialize_unit_score(candidate.total_score),
        "total_score_pct": serialize_pct_score(candidate.total_score),
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _build_unified_country_basis_payload(
    *,
    result: ControlInferenceResult,
    context: ControlInferenceContext,
) -> str:
    winning_candidate = next(
        (
            candidate
            for candidate in result.candidates
            if candidate.controller_entity_id == result.actual_controller_entity_id
        ),
        None,
    )
    if winning_candidate is None:
        total_score = "0.0000"
        total_confidence = "0.0000"
        semantic_flags = None
        top_paths = []
        evidence_summary = (
            ["joint control prevents unique attribution"]
            if result.attribution_type == "joint_control"
            else ["fallback to incorporation country because no controlling candidate met threshold"]
        )
    else:
        total_score = serialize_unit_score(winning_candidate.total_score)
        total_confidence = serialize_unit_score(winning_candidate.total_confidence)
        semantic_flags = _semantic_flags_for_storage(winning_candidate.semantic_flags)
        top_paths = [
            _serialize_unified_path(path_state, context=context)
            for path_state in winning_candidate.top_paths
        ]
        evidence_summary = list(winning_candidate.evidence_summary)

    payload = {
        "analysis": "unified_control_inference_v1",
        "aggregator": result.aggregator,
        "as_of": context.as_of.isoformat(),
        "classification": result.attribution_type,
        "attribution_type": result.attribution_type,
        "actual_control_country": result.actual_control_country,
        "actual_controller_entity_id": result.actual_controller_entity_id,
        "joint_controller_entity_ids": list(result.joint_controller_entity_ids),
        "semantic_flags": semantic_flags,
        "top_paths": top_paths,
        "evidence_summary": evidence_summary,
        "total_confidence": total_confidence,
        "total_score": total_score,
        "total_score_pct": _serialize_pct_from_any(total_score),
        "top_candidates": [
            {
                "controller_entity_id": candidate.controller_entity_id,
                "controller_name": context.entity_map[candidate.controller_entity_id].entity_name,
                "classification": _control_type_from_candidate(candidate),
                "control_mode": candidate.control_mode,
                "semantic_flags": _semantic_flags_for_storage(candidate.semantic_flags),
                "total_confidence": serialize_unit_score(candidate.total_confidence),
                "total_score": serialize_unit_score(candidate.total_score),
                "total_score_pct": serialize_pct_score(candidate.total_score),
            }
            for candidate in result.candidates[:5]
        ],
    }
    return json.dumps(payload, ensure_ascii=False, sort_keys=True)


def _apply_unified_company_analysis_records(
    db: Session,
    result: ControlInferenceResult,
    *,
    context: ControlInferenceContext,
) -> dict:
    company = result.company
    target_entity = result.target_entity

    (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company.id)
        .filter(ControlRelationship.notes.like("AUTO:%"))
        .delete(synchronize_session=False)
    )
    (
        db.query(CountryAttribution)
        .filter(CountryAttribution.company_id == company.id)
        .filter(CountryAttribution.notes.like("AUTO:%"))
        .delete(synchronize_session=False)
    )

    for candidate in result.candidates:
        controller_entity = context.entity_map[candidate.controller_entity_id]
        is_actual_controller = (
            result.actual_controller_entity_id is not None
            and candidate.controller_entity_id == result.actual_controller_entity_id
        )
        semantic_flags = _semantic_flags_for_storage(candidate.semantic_flags)
        review_status = (
            "needs_review"
            if semantic_flags and "needs_review" in semantic_flags
            else "auto"
        )

        db.add(
            ControlRelationship(
                company_id=company.id,
                controller_entity_id=controller_entity.id,
                controller_name=controller_entity.entity_name,
                controller_type=controller_entity.entity_type,
                control_type=_control_type_from_candidate(candidate),
                control_ratio=unit_to_pct(candidate.total_score),
                control_path=_serialize_unified_paths(
                    candidate.path_states,
                    context=context,
                ),
                is_actual_controller=is_actual_controller,
                basis=_build_unified_basis_payload(
                    result=result,
                    candidate=candidate,
                    context=context,
                ),
                notes=AUTO_NOTE,
                control_mode=candidate.control_mode,
                semantic_flags=(
                    json.dumps(semantic_flags, ensure_ascii=False, sort_keys=True)
                    if semantic_flags is not None
                    else None
                ),
                review_status=review_status,
            )
        )

    attribution_type = result.attribution_type
    if attribution_type.startswith("fallback_"):
        source_mode = "fallback_rule"
    elif attribution_type in {"mixed_control", "joint_control"}:
        source_mode = "hybrid"
    else:
        source_mode = "control_chain_analysis"

    db.add(
        CountryAttribution(
            company_id=company.id,
            incorporation_country=company.incorporation_country,
            listing_country=company.listing_country,
            actual_control_country=result.actual_control_country,
            attribution_type=attribution_type,
            basis=_build_unified_country_basis_payload(
                result=result,
                context=context,
            ),
            is_manual=False,
            notes=AUTO_NOTE,
            source_mode=source_mode,
        )
    )

    db.flush()

    return {
        "company_id": company.id,
        "target_entity_id": target_entity.id,
        "as_of": context.as_of.isoformat(),
        "actual_controller_entity_id": result.actual_controller_entity_id,
        "control_relationship_count": len(result.candidates),
        "country_attribution_type": attribution_type,
        "engine": "unified_control_inference_v1",
        "controller_candidates": [
            {
                "entity_id": candidate.controller_entity_id,
                "entity_name": context.entity_map[candidate.controller_entity_id].entity_name,
                "control_level": candidate.control_level,
                "control_mode": candidate.control_mode,
                "semantic_flags": _semantic_flags_for_storage(candidate.semantic_flags),
                "total_confidence": serialize_unit_score(candidate.total_confidence),
                "total_score_pct": serialize_pct_score(candidate.total_score),
                "path_count": len(candidate.path_states),
                "is_actual_controller": (
                    result.actual_controller_entity_id is not None
                    and candidate.controller_entity_id == result.actual_controller_entity_id
                ),
            }
            for candidate in result.candidates
        ],
    }


def _refresh_company_control_analysis_with_unified_context(
    db: Session,
    company_id: int,
    *,
    context: ControlInferenceContext,
    max_depth: int,
    min_path_ratio_pct: Decimal,
    majority_threshold_pct: Decimal,
    disclosure_threshold_pct: Decimal,
) -> dict:
    result = infer_controllers(
        context,
        company_id,
        max_depth=max_depth,
        min_path_score=_pct_threshold_to_unit(min_path_ratio_pct),
        control_threshold=_pct_threshold_to_unit(majority_threshold_pct),
        significant_threshold=Decimal("0.20"),
        disclosure_threshold=_pct_threshold_to_unit(disclosure_threshold_pct),
        aggregator="sum_cap",
    )
    return _apply_unified_company_analysis_records(
        db,
        result,
        context=context,
    )


def refresh_company_control_analysis(
    db: Session,
    company_id: int,
    as_of: date | datetime | None = None,
    max_depth: int = 10,
    min_path_ratio_pct: Decimal = Decimal("0.01"),
    majority_threshold_pct: Decimal = Decimal("50.0"),
    disclosure_threshold_pct: Decimal = Decimal("25.0"),
) -> dict:
    if max_depth < 1:
        raise ValueError("max_depth must be at least 1.")
    if min_path_ratio_pct < ZERO:
        raise ValueError("min_path_ratio_pct must be non-negative.")
    if _use_unified_control_engine():
        unified_context = build_control_context(db, as_of)
        try:
            result = _refresh_company_control_analysis_with_unified_context(
                db,
                company_id,
                context=unified_context,
                max_depth=max_depth,
                min_path_ratio_pct=min_path_ratio_pct,
                majority_threshold_pct=majority_threshold_pct,
                disclosure_threshold_pct=disclosure_threshold_pct,
            )
            db.commit()
            return result
        except Exception:
            db.rollback()
            if not _allow_legacy_fallback():
                raise

    legacy_context = build_ownership_analysis_context(db, as_of)

    try:
        result = _refresh_company_control_analysis_with_context(
            db,
            company_id,
            context=legacy_context,
            max_depth=max_depth,
            min_path_ratio_pct=min_path_ratio_pct,
            majority_threshold_pct=majority_threshold_pct,
            disclosure_threshold_pct=disclosure_threshold_pct,
        )
        db.commit()
        return result
    except Exception:
        db.rollback()
        raise


def refresh_all_companies_control_analysis(
    db: Session,
    batch_size: int = 100,
) -> dict:
    if batch_size < 1:
        raise ValueError("batch_size must be at least 1.")

    started_at = perf_counter()
    use_unified_engine = _use_unified_control_engine()
    context = (
        build_control_context(db)
        if use_unified_engine
        else build_ownership_analysis_context(db)
    )
    company_ids = sorted(context.company_map)
    total = len(company_ids)
    success_count = 0
    failed_count = 0
    per_company_durations: list[float] = []

    print("[START] control analysis")

    for batch_start in range(0, total, batch_size):
        batch_end = min(batch_start + batch_size, total)
        batch_company_ids = company_ids[batch_start:batch_end]
        batch_success_count = 0

        print(f"[BATCH] processing {batch_start + 1}-{batch_end} / {total}")

        for company_id in batch_company_ids:
            company_started_at = perf_counter()
            try:
                with db.begin_nested():
                    if use_unified_engine:
                        result = _refresh_company_control_analysis_with_unified_context(
                            db,
                            company_id,
                            context=context,
                            max_depth=10,
                            min_path_ratio_pct=Decimal("0.01"),
                            majority_threshold_pct=Decimal("50.0"),
                            disclosure_threshold_pct=Decimal("25.0"),
                        )
                    else:
                        result = _refresh_company_control_analysis_with_context(
                            db,
                            company_id,
                            context=context,
                            max_depth=10,
                            min_path_ratio_pct=Decimal("0.01"),
                            majority_threshold_pct=Decimal("50.0"),
                            disclosure_threshold_pct=Decimal("25.0"),
                        )
                success_count += 1
                batch_success_count += 1
                print(
                    f"[COMPANY] {company_id} done, "
                    f"controllers={result['control_relationship_count']}"
                )
            except Exception as exc:
                failed_count += 1
                db.expire_all()
                print(f"[COMPANY] {company_id} failed: {exc}")
            finally:
                per_company_durations.append(perf_counter() - company_started_at)

        try:
            db.commit()
            print(f"[BATCH] committed {len(batch_company_ids)}")
        except Exception as exc:
            db.rollback()
            success_count -= batch_success_count
            failed_count += batch_success_count
            print(
                f"[BATCH] commit failed {batch_start + 1}-{batch_end} / {total}: {exc}"
            )

    total_duration_seconds = perf_counter() - started_at
    average_duration_seconds = (
        sum(per_company_durations) / len(per_company_durations)
        if per_company_durations
        else 0.0
    )

    print(f"[END] total processed = {total}")

    return {
        "total_processed": total,
        "success_count": success_count,
        "failed_count": failed_count,
        "average_duration_seconds": average_duration_seconds,
        "total_duration_seconds": total_duration_seconds,
    }


def _normalize_path_edges(
    *,
    path_item: dict,
    relation_type_fallback: str,
) -> list[dict]:
    path_entity_ids = path_item.get("path_entity_ids") or []
    raw_edges = path_item.get("edges")
    if isinstance(raw_edges, list) and raw_edges:
        normalized_edges = []
        for index, edge in enumerate(raw_edges):
            normalized_edges.append(
                {
                    "structure_id": edge.get("structure_id"),
                    "from_entity_id": edge.get("from_entity_id")
                    if edge.get("from_entity_id") is not None
                    else (
                        path_entity_ids[index]
                        if index < len(path_entity_ids)
                        else None
                    ),
                    "to_entity_id": edge.get("to_entity_id")
                    if edge.get("to_entity_id") is not None
                    else (
                        path_entity_ids[index + 1]
                        if index + 1 < len(path_entity_ids)
                        else None
                    ),
                    "relation_type": edge.get("relation_type") or relation_type_fallback,
                    "relation_role": edge.get("relation_role"),
                    "numeric_factor": _serialize_probability(edge.get("numeric_factor")),
                    "semantic_factor": _serialize_probability(
                        edge.get("semantic_factor")
                    )
                    or "1.0000",
                    "confidence_weight": _serialize_probability(
                        edge.get("confidence_weight")
                    )
                    or "1.0000",
                    "flags": _parse_json_list(edge.get("flags")) or [],
                    "evidence_summary": edge.get("evidence_summary"),
                }
            )
        return normalized_edges

    raw_edge_factors = path_item.get("edge_factors")
    if isinstance(raw_edge_factors, list) and raw_edge_factors:
        normalized_edges = []
        for index, edge in enumerate(raw_edge_factors):
            normalized_edges.append(
                {
                    "structure_id": edge.get("structure_id"),
                    "from_entity_id": (
                        path_entity_ids[index]
                        if index < len(path_entity_ids)
                        else None
                    ),
                    "to_entity_id": (
                        path_entity_ids[index + 1]
                        if index + 1 < len(path_entity_ids)
                        else None
                    ),
                    "relation_type": edge.get("relation_type") or relation_type_fallback,
                    "relation_role": edge.get("relation_role"),
                    "numeric_factor": _serialize_probability(edge.get("numeric_factor")),
                    "semantic_factor": _serialize_probability(
                        edge.get("semantic_factor")
                    )
                    or "1.0000",
                    "confidence_weight": _serialize_probability(
                        edge.get("confidence_weight")
                    )
                    or "1.0000",
                    "flags": _parse_json_list(edge.get("flags")) or [],
                    "evidence_summary": edge.get("evidence_summary"),
                }
            )
        return normalized_edges

    raw_edge_ratios = path_item.get("edge_holding_ratio_pct") or []
    if isinstance(raw_edge_ratios, list) and raw_edge_ratios:
        return [
            {
                "structure_id": None,
                "from_entity_id": (
                    path_entity_ids[index] if index < len(path_entity_ids) else None
                ),
                "to_entity_id": (
                    path_entity_ids[index + 1]
                    if index + 1 < len(path_entity_ids)
                    else None
                ),
                "relation_type": relation_type_fallback,
                "relation_role": "ownership"
                if relation_type_fallback == "equity"
                else None,
                "numeric_factor": _serialize_probability(ratio),
                "semantic_factor": "1.0000",
                "confidence_weight": "1.0000",
                "flags": [relation_type_fallback] if relation_type_fallback else [],
                "evidence_summary": None,
            }
            for index, ratio in enumerate(raw_edge_ratios)
        ]

    return []


def _normalize_control_path_payload(
    payload: list | dict | str | None,
    *,
    control_mode: str | None,
    semantic_flags: list[str] | None,
) -> list | dict | str | None:
    if isinstance(payload, str):
        payload = _deserialize_json(payload)
    if not isinstance(payload, list):
        return payload

    relation_type_fallback = (
        "equity"
        if control_mode in {None, "numeric"}
        else (
            "board_control"
            if semantic_flags and "board_control" in semantic_flags
            else "agreement"
        )
    )
    normalized_paths = []
    for path_item in payload:
        if not isinstance(path_item, dict):
            normalized_paths.append(path_item)
            continue

        item_relation_type_fallback = relation_type_fallback
        if isinstance(path_item.get("edge_holding_ratio_pct"), list):
            item_relation_type_fallback = "equity"

        normalized_edges = _normalize_path_edges(
            path_item=path_item,
            relation_type_fallback=item_relation_type_fallback,
        )
        path_entity_ids = path_item.get("path_entity_ids") or []
        path_score = (
            _serialize_probability(path_item.get("path_score"))
            or _serialize_probability(path_item.get("path_score_pct"))
            or _serialize_probability(path_item.get("path_ratio_pct"))
            or "0.0000"
        )
        normalized_paths.append(
            {
                "path_entity_ids": path_entity_ids,
                "path_entity_names": path_item.get("path_entity_names") or [],
                "edge_ids": path_item.get("edge_ids")
                or [edge.get("structure_id") for edge in normalized_edges],
                "edges": normalized_edges,
                "numeric_prod": _serialize_probability(path_item.get("numeric_prod"))
                or (
                    path_score
                    if control_mode == "numeric"
                    else "1.0000"
                ),
                "semantic_prod": _serialize_probability(path_item.get("semantic_prod"))
                or (
                    "1.0000"
                    if control_mode == "numeric"
                    else path_score
                ),
                "confidence_prod": _serialize_probability(
                    path_item.get("confidence_prod")
                )
                or "1.0000",
                "path_score": path_score,
                "path_score_pct": (
                    path_item.get("path_score_pct")
                    or path_item.get("path_ratio_pct")
                    or _serialize_pct_from_any(path_score)
                ),
                "semantic_flags": _parse_json_list(
                    path_item.get("semantic_flags")
                )
                or semantic_flags,
            }
        )

    return normalized_paths


def _normalize_basis_payload(
    payload: dict | str | None,
    *,
    classification: str | None,
    control_mode: str | None,
    semantic_flags: list[str] | None,
    control_path: list | dict | str | None,
    control_ratio: str | None,
) -> dict | str | None:
    parsed = payload
    if isinstance(payload, str):
        parsed = _deserialize_json(payload)
    if not isinstance(parsed, dict):
        return parsed

    total_score = (
        parsed.get("total_score")
        or _serialize_probability(parsed.get("total_score_pct"))
        or _serialize_probability(parsed.get("total_ratio_pct"))
        or _serialize_probability(control_ratio)
        or "0.0000"
    )
    normalized_paths = _normalize_control_path_payload(
        parsed.get("top_paths") or control_path,
        control_mode=parsed.get("control_mode") or control_mode,
        semantic_flags=_parse_json_list(parsed.get("semantic_flags")) or semantic_flags,
    )

    return {
        **parsed,
        "aggregator": parsed.get("aggregator") or "sum_cap",
        "classification": _canonical_control_type(
            parsed.get("classification") or classification
        )
        or classification,
        "control_mode": parsed.get("control_mode") or control_mode,
        "semantic_flags": _parse_json_list(parsed.get("semantic_flags")) or semantic_flags,
        "top_paths": normalized_paths if isinstance(normalized_paths, list) else [],
        "evidence_summary": parsed.get("evidence_summary") or [],
        "total_confidence": _serialize_probability(parsed.get("total_confidence"))
        or "1.0000",
        "total_score": total_score,
        "total_score_pct": parsed.get("total_score_pct")
        or _serialize_pct_from_any(total_score),
    }


def _normalize_country_basis_payload(
    payload: dict | str | None,
    *,
    attribution_type: str | None,
) -> dict | str | None:
    parsed = payload
    if isinstance(payload, str):
        parsed = _deserialize_json(payload)
    if not isinstance(parsed, dict):
        return parsed

    total_score = (
        parsed.get("total_score")
        or _serialize_probability(parsed.get("total_score_pct"))
        or "0.0000"
    )
    top_paths = _normalize_control_path_payload(
        parsed.get("top_paths"),
        control_mode=parsed.get("control_mode"),
        semantic_flags=_parse_json_list(parsed.get("semantic_flags")),
    )
    top_candidates = parsed.get("top_candidates")
    if isinstance(top_candidates, list):
        normalized_top_candidates = []
        for item in top_candidates:
            if not isinstance(item, dict):
                continue
            normalized_top_candidates.append(
                {
                    **item,
                    "classification": _canonical_control_type(
                        item.get("classification")
                    )
                    or item.get("classification"),
                    "semantic_flags": _parse_json_list(item.get("semantic_flags")),
                    "total_confidence": _serialize_probability(
                        item.get("total_confidence")
                    )
                    or "0.0000",
                    "total_score": _serialize_probability(item.get("total_score"))
                    or _serialize_probability(item.get("total_score_pct"))
                    or "0.0000",
                    "total_score_pct": item.get("total_score_pct")
                    or _serialize_pct_from_any(item.get("total_score")),
                }
            )
    else:
        normalized_top_candidates = []

    return {
        **parsed,
        "classification": _canonical_attribution_type(
            parsed.get("classification") or attribution_type
        )
        or attribution_type,
        "attribution_type": _canonical_attribution_type(
            parsed.get("attribution_type") or attribution_type
        )
        or attribution_type,
        "semantic_flags": _parse_json_list(parsed.get("semantic_flags")),
        "top_paths": top_paths if isinstance(top_paths, list) else [],
        "evidence_summary": parsed.get("evidence_summary") or [],
        "total_confidence": _serialize_probability(parsed.get("total_confidence"))
        or "0.0000",
        "total_score": total_score,
        "total_score_pct": parsed.get("total_score_pct")
        or _serialize_pct_from_any(total_score),
        "top_candidates": normalized_top_candidates,
    }


def _serialize_control_relationship_response(
    relationship: ControlRelationship,
) -> dict:
    semantic_flags = _parse_json_list(relationship.semantic_flags)
    control_mode = relationship.control_mode
    control_type = _canonical_control_type(relationship.control_type)
    control_ratio = _serialize_ratio(relationship.control_ratio)
    control_path = _normalize_control_path_payload(
        relationship.control_path,
        control_mode=control_mode,
        semantic_flags=semantic_flags,
    )
    return {
        "id": relationship.id,
        "company_id": relationship.company_id,
        "controller_entity_id": relationship.controller_entity_id,
        "controller_name": relationship.controller_name,
        "controller_type": relationship.controller_type,
        "control_type": control_type,
        "control_ratio": control_ratio,
        "control_path": control_path,
        "is_actual_controller": relationship.is_actual_controller,
        "basis": _normalize_basis_payload(
            relationship.basis,
            classification=control_type,
            control_mode=control_mode,
            semantic_flags=semantic_flags,
            control_path=control_path,
            control_ratio=control_ratio,
        ),
        "notes": relationship.notes,
        "control_mode": control_mode,
        "semantic_flags": semantic_flags,
        "review_status": relationship.review_status,
        "created_at": relationship.created_at.isoformat(),
        "updated_at": relationship.updated_at.isoformat(),
    }


def get_company_control_chain_data(db: Session, company_id: int) -> dict:
    relationships = (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company_id)
        .order_by(
            ControlRelationship.control_ratio.is_(None),
            ControlRelationship.control_ratio.desc(),
            ControlRelationship.id.asc(),
        )
        .all()
    )

    return {
        "company_id": company_id,
        "controller_count": len(relationships),
        "control_relationships": [
            _serialize_control_relationship_response(relationship)
            for relationship in relationships
        ],
    }


def get_company_actual_controller_data(db: Session, company_id: int) -> dict:
    relationships = (
        db.query(ControlRelationship)
        .filter(ControlRelationship.company_id == company_id)
        .filter(ControlRelationship.is_actual_controller.is_(True))
        .order_by(
            ControlRelationship.control_ratio.is_(None),
            ControlRelationship.control_ratio.desc(),
            ControlRelationship.id.asc(),
        )
        .all()
    )

    return {
        "company_id": company_id,
        "controller_count": len(relationships),
        "actual_controllers": [
            _serialize_control_relationship_response(relationship)
            for relationship in relationships
        ],
    }


def get_company_country_attribution_data(db: Session, company_id: int) -> dict:
    country_attribution = (
        db.query(CountryAttribution)
        .filter(CountryAttribution.company_id == company_id)
        .order_by(CountryAttribution.id.desc())
        .first()
    )

    if country_attribution is None:
        return {
            "company_id": company_id,
            "message": "No country attribution data found for this company.",
            "actual_control_country": None,
            "attribution_type": None,
            "basis": None,
            "source_mode": None,
        }

    attribution_type = _canonical_attribution_type(country_attribution.attribution_type)
    return {
        "company_id": company_id,
        "actual_control_country": country_attribution.actual_control_country,
        "attribution_type": attribution_type,
        "basis": _normalize_country_basis_payload(
            country_attribution.basis,
            attribution_type=attribution_type,
        ),
        "source_mode": country_attribution.source_mode,
    }
